name: edificators_hub_mobile
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # -- dependencies --
  file_picker:
  fluttertoast:
  bottom_navy_bar: ^6.0.0
  # flutter_datetime_picker: ^2.0.1
  intl:
  provider: ^6.1.2
  font_awesome_flutter: ^10.1.0
  http:
  flutter_spinkit:
  shared_preferences:
  image_picker:
  http_parser:
  flutter_native_splash:
  internet_connection_checker:
  mime:
  cached_network_image:
  firebase_core:
  cloud_firestore:
  # -- dependencies --

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: fonts/Montserrat-Light.ttf
        weight: 300

flutter_native_splash:
  color: "#ffffff"
  image: images/logo.png
  android: true
  ios: true
  fullscreen: true
